


title: SPREYD
description: spreyd the data, don't sprinkle it.
# author: _
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spreyd.com" # the base hostname & protocol for your site, 
#twitter_username: twitter
#github_username:  github

# Build settings
theme: minima
plugins:
  - jekyll-admin
  - jekyll-feed

includes_dir: _includes/img
includes_dir: _includes

#exclude:
#  - _includes/img
  
jekyll_admin:
  hidden_links:
#    - posts
#   - pages
#   - staticfiles
#    - datafiles
#    - configuration
  homepage: "posts"
  
header_pages:
   - kollektiv.markdown
   - tracker.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
